version: "3.9"

services:
  mobileguru_web:
    build: .
    container_name: mobileguru_web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://suites.albadar.cloud/api/v1
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
